'use client';import {useEffect,useMemo,useState} from 'react';import {scenarios} from '@/content';import {applyAction,averageScore,currentNode,startRun} from '@/game/engine';import {HistoryEntry,Run,Scenario} from '@/game/model';import {loadHistory,saveHistory} from '@/storage/history';
type Screen='HOME'|'RUN'|'RESULT';
const actionLabels:Record<string,string>={INVESTIGATE:'조사',MITIGATE:'완화',CHANGE:'변경',RESTART:'재시작',ROLLBACK:'롤백',KILL:'종료',WAIT:'대기',ESCALATE:'에스컬레이션'};
const categoryLabels:Record<string,string>={DATABASE:'데이터베이스',BACKEND:'백엔드',PLATFORM:'플랫폼',NETWORK:'네트워크',CONCURRENCY:'동시성'};
const scoreLabels:Record<string,string>={diagnosis:'진단',safety:'안전',efficiency:'효율',understanding:'이해'};
export default function Game(){const [screen,setScreen]=useState<Screen>('HOME');const [scenario,setScenario]=useState<Scenario>();const [run,setRun]=useState<Run>();const [history,setHistory]=useState<HistoryEntry[]>([]);useEffect(()=>setHistory(loadHistory(localStorage)),[]);const node=useMemo(()=>scenario&&run?currentNode(scenario,run):undefined,[scenario,run]);
function begin(){const next=scenarios[Math.floor(Math.random()*scenarios.length)];setScenario(next);setRun(startRun(next));setScreen('RUN')}
function act(id:string){if(!scenario||!run)return;const next=applyAction(scenario,run,id);setRun(next);if(next.status!=='ACTIVE'){const entry:HistoryEntry={scenarioId:scenario.id,title:scenario.title,date:new Date().toISOString(),result:next.status,score:averageScore(next),duration:next.elapsedGameTime,actions:next.actions.length,skills:scenario.skills};const updated=[entry,...history];setHistory(updated);saveHistory(localStorage,updated);setScreen('RESULT')}}
if(screen==='HOME')return <section className="home"><p className="eyebrow">인시던트 시뮬레이션</p><h1>IdleQuest</h1><p className="tagline">잠깐의 시간, 하나의 인시던트. 결정은 당신의 몫입니다.</p><button className="primary hero" onClick={begin}>랜덤 인시던트 시작</button><p className="mode">랜덤 / 편안함 · {scenarios.length} 개 인시던트</p><section className="panel"><h2>최근 플레이</h2>{history.length===0?<p className="muted">완료한 인시던트가 여기에 표시됩니다.</p>:history.slice(0,5).map((h,i)=><div className="recent" key={h.date+i}><span aria-hidden>{h.result==='RESOLVED'?'✓':'×'}</span><strong>{scenarios.find(s=>s.id===h.scenarioId)?.title??h.title}</strong><small>{h.score} · {h.duration}분</small></div>)}</section></section>;
if(screen==='RUN'&&scenario&&run&&node)return <section><header className="runhead"><button className="quiet" onClick={()=>setScreen('HOME')} aria-label="플레이 나가기">← 나가기</button><time>T+{run.elapsedGameTime}분</time></header><p className="eyebrow">진행 중인 인시던트 · {categoryLabels[scenario.category]??scenario.category}</p><h1>{scenario.title}</h1><div className="panel incident"><p>{node.text}</p>{node.observations.map(o=><div className="observation" key={o}>{o}</div>)}</div>{run.timeline.length>1&&<div className="consequence" role="status"><strong>최근 결과</strong><p>{run.timeline.at(-1)?.label}</p></div>}<h2>조사 및 조치</h2><div className="actions">{node.actions.map(a=><button key={a.id} onClick={()=>act(a.id)} className={a.type==='INVESTIGATE'?'action':'action risky'}><small>{actionLabels[a.type]??a.type}</small>{a.label}</button>)}</div><details><summary>인시던트 기록 ({run.timeline.length})</summary><ol className="timeline">{run.timeline.map((e,i)=><li key={i}><time>T+{e.minute}</time>{e.label}</li>)}</ol></details></section>;
if(screen==='RESULT'&&scenario&&run){const good=run.scores.safety>=60;return <section><p className="eyebrow">플레이 완료</p><h1>{run.status==='RESOLVED'?'인시던트 해결':'인시던트 에스컬레이션'}</h1><p className="tagline">{scenario.title} · {run.elapsedGameTime}분 · {run.actions.length}회 행동</p><div className="scoregrid">{Object.entries(run.scores).map(([k,v])=><div key={k}><strong>{v}</strong><span>{scoreLabels[k]??k}</span></div>)}</div><div className="panel"><h2>근본 원인</h2><p>{scenario.rootCause}</p><h2>{good?'잘한 점':'개선할 점'}</h2><p>{good?'증거를 수집하면서 운영 위험을 안정적으로 관리했습니다.':'충분한 증거를 확보하기 전 운영 환경을 변경해 사용자 영향이 커졌습니다.'}</p><h2>학습 노트</h2><ul>{scenario.review.learningNotes.map(n=><li key={n}>{n}</li>)}</ul></div><details open><summary>행동 타임라인</summary><ol className="timeline">{run.timeline.map((e,i)=><li key={i}><time>T+{e.minute}</time>{e.label}</li>)}</ol></details><button className="primary hero" onClick={begin}>다른 인시던트 플레이</button><button className="quiet full" onClick={()=>setScreen('HOME')}>홈으로 돌아가기</button></section>}return null}
